services:
  glyphhold:
    image: ghcr.io/dosk3n/glyphhold:0.1.0-alpha
    container_name: glyphhold
    ports:
      - "5995:5995"
    volumes:
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped
